# Markdownlint configuration
# Сбалансированная конфигурация для качественной документации

# === ОТКЛЮЧЕННЫЕ ПРАВИЛА ===

# MD013: Длина строки - мониторы сейчас широкие
MD013: false

# MD033: HTML в Markdown - MkDocs требует HTML для некоторых функций
MD033: false

# MD038: Пробелы внутри inline кода - иногда нужны
MD038: false

# MD041: Первая строка должна быть заголовком - у нас там frontmatter
MD041: false

# MD046: Стиль блоков кода - MkDocs tabs используют отступы
MD046: false

# === НАСТРОЕННЫЕ ПРАВИЛА ===

# MD024: Одинаковые заголовки разрешены, если не соседи
MD024:
  siblings_only: true

# MD029: Нумерация списков - разрешаем 1. 1. 1. для автоперенумерации
# (когда добавляешь пункт в середину, не надо вручную менять все номера)
MD029:
  style: "one"

# === ВКЛЮЧЕННЫЕ ПРАВИЛА (оставляем как есть) ===

# MD001-MD003: Структура заголовков (правильная иерархия)
# MD022: Пустые строки вокруг заголовков (для правильного отображения)
# MD025: Только один H1 на документ (правильная структура)
# MD031: Пустые строки вокруг блоков кода (для правильного отображения)
# MD032: Пустые строки вокруг списков (для правильного отображения)
# MD009: Убирать пробелы в конце строк
# MD014: Не ставить $ перед командами (мешает копированию)
# MD034: URL должны быть ссылками, не голыми
# MD040: Блоки кода должны иметь язык
