#!/usr/bin/env python3
"""Generate Algolia search widget files for any supported site generator.

Supported generators: mkdocs, docusaurus, hugo, vitepress, custom.

For each generator, this script produces the correct configuration files,
JS/CSS assets, and installation instructions so Algolia search works
out of the box after provisioning.

Usage:
  python3 scripts/generate_algolia_widget.py \\
    --generator mkdocs \\
    --app-id 68IGGT3CVI \\
    --search-key 12bd532b0a8c9dd7405a892e365c9e6b \\
    --index-name veridoc_docs \\
    --output-dir client-repo/
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

# ---------------------------------------------------------------------------
# Generator-specific config generators
# ---------------------------------------------------------------------------


def _mkdocs_files(cfg: dict[str, str]) -> dict[str, str]:
    """Generate files for MkDocs Material."""
    # Copy our own Algolia overlay widget
    js_src = REPO_ROOT / "docs" / "assets" / "javascripts" / "algolia-search.js"
    css_src = REPO_ROOT / "docs" / "stylesheets" / "algolia-search.css"

    js_content = js_src.read_text(encoding="utf-8") if js_src.exists() else ""
    css_content = css_src.read_text(encoding="utf-8") if css_src.exists() else ""

    mkdocs_patch = f"""\
# -- Algolia Search (auto-generated by VeriOps) --
# Add these lines to your mkdocs.yml:
#
# extra_css:
#   - stylesheets/algolia-search.css
#
# extra_javascript:
#   - assets/javascripts/algolia-search.js
#
# extra:
#   algolia:
#     app_id: {cfg['app_id']}
#     api_key: {cfg['search_key']}
#     index_name: {cfg['index_name']}
"""

    return {
        "docs/assets/javascripts/algolia-search.js": js_content,
        "docs/stylesheets/algolia-search.css": css_content,
        "docs/_algolia_mkdocs_patch.yml": mkdocs_patch,
    }


def _docusaurus_files(cfg: dict[str, str]) -> dict[str, str]:
    """Generate files for Docusaurus v3."""
    config_patch = f"""\
// -- Algolia Search (auto-generated by VeriOps) --
// Add to your docusaurus.config.js under themeConfig:
//
// themeConfig: {{
//   algolia: {{
//     appId: '{cfg['app_id']}',
//     apiKey: '{cfg['search_key']}',
//     indexName: '{cfg['index_name']}',
//     contextualSearch: true,
//     searchPagePath: 'search',
//   }},
// }}
//
// Install the theme:
//   npm install @docusaurus/theme-search-algolia
"""

    return {
        "_algolia_docusaurus_patch.js": config_patch,
    }


def _hugo_files(cfg: dict[str, str]) -> dict[str, str]:
    """Generate files for Hugo."""
    # Hugo uses a partial template + config
    config_toml = f"""\
# -- Algolia Search (auto-generated by VeriOps) --
# Add to your hugo.toml / config.toml under [params]:
#
# [params.algolia]
#   appId = "{cfg['app_id']}"
#   apiKey = "{cfg['search_key']}"
#   indexName = "{cfg['index_name']}"
"""

    partial_html = f"""\
<!-- Algolia Search Widget (auto-generated by VeriOps) -->
<!-- Place in layouts/partials/algolia-search.html -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@8/themes/reset-min.css" />
<div id="algolia-search-container">
  <div id="algolia-searchbox"></div>
  <div id="algolia-hits"></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/algoliasearch@4/dist/algoliasearch-lite.umd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4/dist/instantsearch.production.min.js"></script>
<script>
  var client = algoliasearch('{cfg['app_id']}', '{cfg['search_key']}');
  var search = instantsearch({{
    indexName: '{cfg['index_name']}',
    searchClient: client,
  }});
  search.addWidgets([
    instantsearch.widgets.searchBox({{ container: '#algolia-searchbox', placeholder: 'Search docs...' }}),
    instantsearch.widgets.hits({{
      container: '#algolia-hits',
      templates: {{
        item: function(hit) {{
          return '<a href="' + hit.url + '"><strong>' + hit.title + '</strong><br/>' +
                 '<small>' + (hit.description || '').substring(0, 100) + '</small></a>';
        }}
      }}
    }}),
  ]);
  search.start();
</script>
"""

    return {
        "_algolia_hugo_patch.toml": config_toml,
        "layouts/partials/algolia-search.html": partial_html,
    }


def _vitepress_files(cfg: dict[str, str]) -> dict[str, str]:
    """Generate files for VitePress."""
    config_patch = f"""\
// -- Algolia Search (auto-generated by VeriOps) --
// Add to your .vitepress/config.mts under themeConfig:
//
// themeConfig: {{
//   search: {{
//     provider: 'algolia',
//     options: {{
//       appId: '{cfg['app_id']}',
//       apiKey: '{cfg['search_key']}',
//       indexName: '{cfg['index_name']}',
//     }},
//   }},
// }}
"""

    return {
        "_algolia_vitepress_patch.mts": config_patch,
    }


def _custom_files(cfg: dict[str, str]) -> dict[str, str]:
    """Generate standalone widget files for custom/unknown generators."""
    widget_html = f"""\
<!-- Algolia Search Widget (auto-generated by VeriOps) -->
<!-- Include this snippet in your site's <head> or before </body> -->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@8/themes/reset-min.css" />
<link rel="stylesheet" href="algolia-search.css" />

<div id="algolia-search-overlay">
  <div id="algolia-search-modal">
    <div id="algolia-search-header">
      <div id="algolia-searchbox"></div>
      <button id="algolia-search-close" onclick="this.parentElement.parentElement.parentElement.classList.remove('active')">&times;</button>
    </div>
    <div id="algolia-search-body">
      <div id="algolia-hits"></div>
    </div>
    <div id="algolia-search-footer">
      <div id="algolia-stats"></div>
      <a href="https://www.algolia.com" target="_blank" rel="noopener">Search by Algolia</a>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/algoliasearch@4/dist/algoliasearch-lite.umd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4/dist/instantsearch.production.min.js"></script>
<script>
  var client = algoliasearch('{cfg['app_id']}', '{cfg['search_key']}');
  var search = instantsearch({{
    indexName: '{cfg['index_name']}',
    searchClient: client,
  }});
  search.addWidgets([
    instantsearch.widgets.searchBox({{
      container: '#algolia-searchbox',
      placeholder: 'Search documentation...',
      autofocus: true,
    }}),
    instantsearch.widgets.hits({{
      container: '#algolia-hits',
      templates: {{
        item: function(hit) {{
          var title = instantsearch.highlight({{ attribute: 'title', hit: hit }});
          var snippet = (hit._snippetResult && hit._snippetResult.content)
            ? hit._snippetResult.content.value
            : (hit.description || '').substring(0, 120);
          return '<a class="algolia-hit" href="' + (hit.url || '#') + '">' +
            '<div class="algolia-hit-title">' + title + '</div>' +
            '<div class="algolia-hit-snippet">' + snippet + '</div></a>';
        }}
      }}
    }}),
    instantsearch.widgets.stats({{
      container: '#algolia-stats',
      templates: {{
        text: function(data) {{
          return data.nbHits + ' results in ' + data.processingTimeMS + 'ms';
        }}
      }}
    }}),
  ]);
  search.start();

  // Toggle overlay
  document.addEventListener('keydown', function(e) {{
    if (e.key === '/' || e.key === 's') {{
      var tag = (e.target.tagName || '').toLowerCase();
      if (tag === 'input' || tag === 'textarea') return;
      e.preventDefault();
      document.getElementById('algolia-search-overlay').classList.add('active');
    }}
    if (e.key === 'Escape') {{
      document.getElementById('algolia-search-overlay').classList.remove('active');
    }}
  }});
</script>
"""

    css_src = REPO_ROOT / "docs" / "stylesheets" / "algolia-search.css"
    css_content = css_src.read_text(encoding="utf-8") if css_src.exists() else ""

    return {
        "algolia-search-widget.html": widget_html,
        "algolia-search.css": css_content,
    }


GENERATORS = {
    "mkdocs": _mkdocs_files,
    "docusaurus": _docusaurus_files,
    "hugo": _hugo_files,
    "vitepress": _vitepress_files,
    "custom": _custom_files,
}


def generate_widget(
    generator: str,
    app_id: str,
    search_key: str,
    index_name: str,
    output_dir: Path,
) -> list[str]:
    """Generate Algolia widget files for the given site generator.

    Returns list of created file paths (relative to output_dir).
    """
    if generator not in GENERATORS:
        raise ValueError(
            f"Unknown generator '{generator}'. "
            f"Supported: {', '.join(GENERATORS)}"
        )

    cfg = {
        "app_id": app_id,
        "search_key": search_key,
        "index_name": index_name,
    }

    files = GENERATORS[generator](cfg)
    created: list[str] = []

    for rel_path, content in files.items():
        out_path = output_dir / rel_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        created.append(rel_path)

    return created


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Algolia search widget for a site generator"
    )
    parser.add_argument(
        "--generator",
        choices=list(GENERATORS),
        required=True,
        help="Site generator type",
    )
    parser.add_argument("--app-id", required=True, help="Algolia Application ID")
    parser.add_argument("--search-key", required=True, help="Algolia Search-Only API Key")
    parser.add_argument("--index-name", required=True, help="Algolia index name")
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory for generated files",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    created = generate_widget(
        args.generator, args.app_id, args.search_key, args.index_name, output_dir
    )

    print(f"Generated Algolia widget for {args.generator}:")
    for f in created:
        print(f"  {output_dir / f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
