#!/usr/bin/env python3
"""
Generate Docusaurus Configuration

Reads mkdocs.yml (or standalone variables/nav) and produces:
- docusaurus.config.js
- sidebars.js

Converts the MkDocs nav tree into Docusaurus sidebar format.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml


def _load_mkdocs_config(config_path: Path) -> dict:
    """Load and parse mkdocs.yml."""
    text = config_path.read_text(encoding="utf-8")
    return yaml.safe_load(text) or {}


def _load_variables(variables_path: Path) -> dict:
    """Load _variables.yml."""
    if not variables_path.exists():
        return {}
    text = variables_path.read_text(encoding="utf-8")
    return yaml.safe_load(text) or {}


# ---------------------------------------------------------------------------
# Nav conversion: MkDocs nav -> Docusaurus sidebars
# ---------------------------------------------------------------------------

def _md_to_doc_id(md_path: str) -> str:
    """Convert a markdown file path to a Docusaurus doc ID.

    'getting-started/quickstart.md' -> 'getting-started/quickstart'
    'index.md' -> 'index'
    """
    return re.sub(r"\.mdx?$", "", md_path).replace("\\", "/")


def convert_nav_item(item) -> dict | str | None:
    """Convert a single MkDocs nav item to a Docusaurus sidebar item.

    MkDocs nav items can be:
    - str: 'index.md' (unlabeled doc)
    - dict with one key:
        - {'Title': 'path.md'}  (labeled doc)
        - {'Section': [items]}  (category)
    """
    if isinstance(item, str):
        return _md_to_doc_id(item)

    if isinstance(item, dict):
        for label, value in item.items():
            if isinstance(value, str):
                doc_id = _md_to_doc_id(value)
                return {"type": "doc", "id": doc_id, "label": label}
            if isinstance(value, list):
                children = convert_nav_to_sidebar(value)
                # Check if first child is an index page for the category
                link = None
                if children and isinstance(children[0], str):
                    if children[0].endswith("/index") or children[0] == "index":
                        link = {
                            "type": "doc",
                            "id": children[0],
                        }
                        children = children[1:]
                elif children and isinstance(children[0], dict) and children[0].get("type") == "doc":
                    cid = children[0].get("id", "")
                    if cid.endswith("/index") or cid == "index":
                        link = {"type": "doc", "id": cid}
                        children = children[1:]

                category = {
                    "type": "category",
                    "label": label,
                    "items": children,
                }
                if link:
                    category["link"] = link
                return category

    return None


def convert_nav_to_sidebar(nav: list) -> list:
    """Convert the full MkDocs nav list to Docusaurus sidebar items."""
    result = []
    for item in nav:
        converted = convert_nav_item(item)
        if converted is not None:
            result.append(converted)
    return result


# ---------------------------------------------------------------------------
# Config file generation
# ---------------------------------------------------------------------------

def generate_docusaurus_config_js(variables: dict, site_config: dict) -> str:
    """Generate docusaurus.config.js content."""
    product = variables.get("product_name", site_config.get("site_name", "Documentation"))
    site_url = variables.get("docs_url", site_config.get("site_url", "https://example.com"))
    repo_url = site_config.get("repo_url", variables.get("repo_url", ""))

    def js_str(val: str) -> str:
        return val.replace("\\", "\\\\").replace("'", "\\'")

    lines = [
        "// @ts-check",
        "// Generated by Auto-Doc Pipeline -- do not edit manually",
        "",
        "/** @type {import('@docusaurus/types').Config} */",
        "const config = {",
        f"  title: '{js_str(product)}',",
        f"  url: '{js_str(site_url)}',",
        "  baseUrl: '/',",
        "  onBrokenLinks: 'throw',",
        "  onBrokenMarkdownLinks: 'warn',",
        "",
        "  presets: [",
        "    [",
        "      'classic',",
        "      /** @type {import('@docusaurus/preset-classic').Options} */",
        "      ({",
        "        docs: {",
        "          routeBasePath: '/',",
        "          sidebarPath: require.resolve('./sidebars.js'),",
    ]

    if repo_url:
        lines.append(f"          editUrl: '{js_str(repo_url)}/edit/main/',")

    lines.extend([
        "        },",
        "        blog: false,",
        "        theme: {",
        "          customCss: require.resolve('./src/css/custom.css'),",
        "        },",
        "      }),",
        "    ],",
        "  ],",
        "",
        "  themeConfig:",
        "    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */",
        "    ({",
        "      navbar: {",
        f"        title: '{js_str(product)}',",
        "        items: [",
        "          {",
        "            type: 'docSidebar',",
        "            sidebarId: 'docs',",
        "            position: 'left',",
        "            label: 'Documentation',",
        "          },",
        "        ],",
        "      },",
        "      footer: {",
        "        style: 'dark',",
        f"        copyright: 'Built with Auto-Doc Pipeline',",
        "      },",
        "      prism: {",
        "        theme: require('prism-react-renderer').themes.github,",
        "        darkTheme: require('prism-react-renderer').themes.dracula,",
        "        additionalLanguages: ['bash', 'yaml', 'json'],",
        "      },",
        "    }),",
        "};",
        "",
        "module.exports = config;",
        "",
    ])
    return "\n".join(lines)


def generate_sidebars_js(sidebar_items: list) -> str:
    """Generate sidebars.js content from converted nav items."""
    items_json = json.dumps(sidebar_items, indent=4)
    # Indent each line by 4 spaces for nesting inside the object
    indented = "\n".join(
        "    " + line if line.strip() else line
        for line in items_json.split("\n")
    )

    lines = [
        "// @ts-check",
        "// Generated by Auto-Doc Pipeline -- do not edit manually",
        "",
        "/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */",
        "const sidebars = {",
        f"  docs: {indented.strip()},",
        "};",
        "",
        "module.exports = sidebars;",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Docusaurus config from MkDocs config"
    )
    parser.add_argument(
        "--mkdocs-config",
        default="mkdocs.yml",
        help="Path to mkdocs.yml (default: mkdocs.yml)",
    )
    parser.add_argument(
        "--variables",
        default="docs/_variables.yml",
        help="Path to _variables.yml (default: docs/_variables.yml)",
    )
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory for generated files (default: .)",
    )

    args = parser.parse_args()

    mkdocs_path = Path(args.mkdocs_config)
    variables_path = Path(args.variables)
    output_dir = Path(args.output_dir)

    # Load sources
    site_config = _load_mkdocs_config(mkdocs_path) if mkdocs_path.exists() else {}
    variables = _load_variables(variables_path)
    nav = site_config.get("nav", [])

    # Convert nav
    sidebar_items = convert_nav_to_sidebar(nav)

    # Generate files
    output_dir.mkdir(parents=True, exist_ok=True)

    config_js = generate_docusaurus_config_js(variables, site_config)
    config_path = output_dir / "docusaurus.config.js"
    config_path.write_text(config_js, encoding="utf-8")
    print(f"Generated: {config_path}")

    sidebars_js = generate_sidebars_js(sidebar_items)
    sidebars_path = output_dir / "sidebars.js"
    sidebars_path.write_text(sidebars_js, encoding="utf-8")
    print(f"Generated: {sidebars_path}")


if __name__ == "__main__":
    main()
