#!/usr/bin/env python3
"""Render multi-language SDK request snippets from single-source-of-truth specs.

Each ``snippets/sdk/*.req.yml`` describes one API request. This script renders it
into a MkDocs content-tab block (cURL, Python, JavaScript, Go) under
``_snippets/sdk/<id>.md``, resolving base URL and the API-key env var from
``docs/_variables.yml`` so every language variant stays in sync with one source.

Usage:
    python3 scripts/render_sdk_snippets.py            # render all specs
    python3 scripts/render_sdk_snippets.py --check     # verify outputs are current (CI)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

_LANG_ORDER = ["curl", "python", "javascript", "go"]
_LANG_LABEL = {"curl": "cURL", "python": "Python", "javascript": "JavaScript", "go": "Go"}
_LANG_FENCE = {"curl": "bash", "python": "python", "javascript": "javascript", "go": "go"}

_GENERATED_MARKER = "<!-- generated by scripts/render_sdk_snippets.py from snippets/sdk/{src} -- do not edit -->"


def _load_variables(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else {}
    return data if isinstance(data, dict) else {}


def _resolve_endpoint(spec: dict[str, Any], variables: dict[str, Any]) -> tuple[str, str, str]:
    """Return (method, full_url, api_key_env) resolved from spec + variables."""
    method = str(spec.get("method", "GET")).upper()
    base = str(variables.get("api_url", "https://api.example.com")).rstrip("/")
    path = str(spec.get("path", "/"))
    if not path.startswith("/"):
        path = "/" + path
    url = base + path
    query = spec.get("query")
    if isinstance(query, dict) and query:
        pairs = "&".join(f"{k}={v}" for k, v in query.items())
        url = f"{url}?{pairs}"
    env_vars = variables.get("env_vars", {}) if isinstance(variables.get("env_vars"), dict) else {}
    api_key_env = str(env_vars.get("api_key", "PRODUCT_API_KEY"))
    return method, url, api_key_env


def _uses_auth(spec: dict[str, Any]) -> bool:
    return str(spec.get("auth", "bearer")).lower() != "none"


def _body_json(spec: dict[str, Any], indent: int | None = None) -> str:
    body = spec.get("body")
    if not isinstance(body, (dict, list)) or not body:
        return ""
    return json.dumps(body, ensure_ascii=True, indent=indent)


def _render_curl(spec: dict[str, Any], method: str, url: str, api_key_env: str) -> str:
    lines = [f"curl -X {method} {url} \\"]
    if _uses_auth(spec):
        lines.append(f'  -H "Authorization: Bearer ${api_key_env}" \\')
    body = _body_json(spec)
    if body:
        lines.append('  -H "Content-Type: application/json" \\')
        lines.append(f"  -d '{body}'")
    else:
        # Drop the trailing backslash from the last header line.
        lines[-1] = lines[-1].rstrip(" \\")
    return "\n".join(lines)


def _render_python(spec: dict[str, Any], method: str, url: str, api_key_env: str) -> str:
    lines = ["import os", "", "import requests", ""]
    args = [f'    "{url}"']
    headers = []
    if _uses_auth(spec):
        headers.append(f'"Authorization": f"Bearer {{os.environ[\'{api_key_env}\']}}"')
    body = spec.get("body")
    if isinstance(body, (dict, list)) and body:
        args.append(f"    json={_py_literal(body, 1)}")
    if headers:
        args.append("    headers={" + ", ".join(headers) + "}")
    args.append("    timeout=30")
    call = f"resp = requests.{method.lower()}(\n" + ",\n".join(args) + ",\n)"
    lines.append(call)
    lines.append("resp.raise_for_status()")
    lines.append("print(resp.json())")
    return "\n".join(lines)


def _py_literal(value: Any, level: int) -> str:
    """Render a JSON-like value as a Python literal (dict/list/str/num/bool/None)."""
    pad = "    " * level
    inner = "    " * (level + 1)
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = [f'{inner}"{k}": {_py_literal(v, level + 1)}' for k, v in value.items()]
        return "{\n" + ",\n".join(items) + f"\n{pad}}}"
    if isinstance(value, list):
        if not value:
            return "[]"
        items = [f"{inner}{_py_literal(v, level + 1)}" for v in value]
        return "[\n" + ",\n".join(items) + f"\n{pad}]"
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)
    return str(value)


def _render_javascript(spec: dict[str, Any], method: str, url: str, api_key_env: str) -> str:
    headers = ['    "Content-Type": "application/json",']
    if _uses_auth(spec):
        headers.insert(0, f'    "Authorization": `Bearer ${{process.env.{api_key_env}}}`,')
    opts = [f'  method: "{method}",', "  headers: {", *headers, "  },"]
    body = _body_json(spec, indent=2)
    if body:
        indented = body.replace("\n", "\n  ")
        opts.append(f"  body: JSON.stringify({indented}),")
    lines = [
        f'const resp = await fetch("{url}", {{',
        *opts,
        "});",
        "const data = await resp.json();",
        "console.log(data);",
    ]
    return "\n".join(lines)


def _render_go(spec: dict[str, Any], method: str, url: str, api_key_env: str) -> str:
    imports = ["\t\"fmt\"", "\t\"net/http\"", "\t\"os\""]
    body = _body_json(spec)
    body_setup = []
    request_body = "nil"
    if body:
        imports.insert(0, "\t\"bytes\"")
        body_setup = [f"\tpayload := []byte(`{body}`)"]
        request_body = "bytes.NewBuffer(payload)"
    lines = [
        "package main",
        "",
        "import (",
        *sorted(imports),
        ")",
        "",
        "func main() {",
        *body_setup,
        f'\treq, _ := http.NewRequest("{method}", "{url}", {request_body})',
    ]
    if _uses_auth(spec):
        lines.append(f'\treq.Header.Set("Authorization", "Bearer "+os.Getenv("{api_key_env}"))')
    if body:
        lines.append('\treq.Header.Set("Content-Type", "application/json")')
    lines += [
        "\tresp, err := http.DefaultClient.Do(req)",
        "\tif err != nil {",
        "\t\tpanic(err)",
        "\t}",
        "\tdefer resp.Body.Close()",
        "\tfmt.Println(resp.Status)",
        "}",
    ]
    return "\n".join(lines)


_RENDERERS = {
    "curl": _render_curl,
    "python": _render_python,
    "javascript": _render_javascript,
    "go": _render_go,
}


def render_spec(spec: dict[str, Any], variables: dict[str, Any], src_name: str) -> str:
    """Render one spec into a Markdown content-tab partial."""
    method, url, api_key_env = _resolve_endpoint(spec, variables)
    languages = spec.get("languages") or _LANG_ORDER
    languages = [lang for lang in languages if lang in _RENDERERS]
    if not languages:
        languages = list(_LANG_ORDER)

    parts = [_GENERATED_MARKER.format(src=src_name), ""]
    title = str(spec.get("title", "")).strip()
    if title:
        parts.append(f"**{title}**")
        parts.append("")
    description = str(spec.get("description", "")).strip()
    if description:
        parts.append(description)
        parts.append("")

    for lang in languages:
        code = _RENDERERS[lang](spec, method, url, api_key_env)
        fence = _LANG_FENCE[lang]
        block = [f'=== "{_LANG_LABEL[lang]}"', "", f"    ```{fence}"]
        block += ["    " + line if line else "" for line in code.split("\n")]
        block += ["    ```", ""]
        parts.extend(block)

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--specs-dir", default="snippets/sdk", help="Directory of *.req.yml specs")
    parser.add_argument("--output-dir", default="_snippets/sdk", help="Where rendered .md partials are written")
    parser.add_argument("--variables", default="docs/_variables.yml", help="SSOT variables file")
    parser.add_argument("--check", action="store_true", help="Verify outputs are current without writing (exit 1 if stale)")
    args = parser.parse_args()

    specs_dir = Path(args.specs_dir)
    output_dir = Path(args.output_dir)
    variables = _load_variables(Path(args.variables))

    specs = sorted(specs_dir.glob("*.req.yml"))
    if not specs:
        print(f"[warn] no *.req.yml specs found in {specs_dir}")
        return 0

    stale: list[str] = []
    written = 0
    for spec_path in specs:
        spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
        if not isinstance(spec, dict) or not spec.get("id"):
            print(f"[error] {spec_path}: missing 'id' or invalid YAML")
            return 2
        rendered = render_spec(spec, variables, spec_path.name)
        out_path = output_dir / f"{spec['id']}.md"
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        if args.check:
            if current != rendered:
                stale.append(str(out_path))
            continue
        if current != rendered:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(rendered, encoding="utf-8")
            written += 1
        print(f"[ok] {spec_path.name} -> {out_path}")

    if args.check:
        if stale:
            print("[stale] rerun scripts/render_sdk_snippets.py; out of date:")
            for path in stale:
                print(f"  - {path}")
            return 1
        print(f"[ok] all {len(specs)} snippet partials are current")
        return 0

    print(f"[done] rendered {len(specs)} spec(s), {written} file(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
